### PR TITLE
Script : Shade of akama movement and soul link fix

### PR DESCRIPTION
**Pull request by coolzoom**
this should fix the soul link visual effect and shade of akama.
I'm not familiar with the scenario, so script tested by one of my friends, use at your own wish or test before use
image

### CODE REVIEW

**Comment by yuanf225** [comment]
I will have time to test it tomorrow or the day after tomorrow. I am very happy that the shade of Akama has been repaired

**Comment by coolzoom** [comment]
All right, Probably can related to this https://github.com/talamortis/OregonCore/issues/2

**Comment by talamortis** [comment]
shouldn't Akama get the threat though as the summoners from the shade should attack Akama? im not 100% sure how black temple used t work

**Comment by coolzoom** [comment]
there might be a structural bug because not sure Why akama shade can’t be added into akama’s threat list before active. You can have a try see there might be a better fix

**Pull request closed without merging**
