### PR TITLE
Cmake: rework macros source groups

### PR DESCRIPTION
**Pull request by ReyDonovan**

### CODE REVIEW

**Review by vhiperdev — APPROVED** [review]

**Comment by talamortis** [comment]
Thanks again @ReyDonovan. @vhiperdev did you test these changes?

**Comment by ReyDonovan** [comment]
im test my PC

**Comment by vhiperdev** [comment]
Building without errors in Windows 10 VS 2017

**Comment by talamortis** [comment]
Ok thank you :), will merge

**Pull request merged**
