### PR TITLE
Core/Auth: support client Cataclysm and MoP

### PR DESCRIPTION
**Pull request by ReyDonovan**
support cataclysm and mop (example realm TBC + Skyfire Mop)

### CODE REVIEW

**Comment by yuanf225** [comment]
Can this change be logged in using a non-243 client?

**Comment by ReyDonovan** [comment]
this allows you to have several realms of different versions on the same login server)

**Comment by talamortis** [comment]
Thanks for this. Be great to have both 2.4.3 and 3.3.5 on the same auth server

**Comment by yuanf225** [comment]
Lee，I don't quite understand what it means to have 243 and 335 at the same time. Is it possible to use 243 and 335 clients to enter the game at the same time?

**Comment by talamortis** [comment]
No, this just allows the user to use 1 auth server to add multiple realms depending on the supported versions.

**Comment by coolzoom** [comment]
i guess have to change the realm database structure to match each other as well, which is also kind of pain:D

**Pull request merged**
