### PR TITLE
Raid/Scripts: Black Temple Fix Start [Reliquary of Souls]

### LINKED ISSUE #19: BlackTemple reliquary of souls
**Revision**: 95952a3 

**Operating system**:ubuntu16

**Current behavior**: The BOSS didn't appear

**Expected behavior**: When the BOSS appears, it will trigger automatically and appear

**Steps to reproduce the problem**:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/72482125-blacktemple-reliquary-of-souls?utm_campaign=plugin&utm_content=tracker%2F91676571&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F91676571&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by vhiperdev**
Fix encounter start and essence phases
Close #19 

Before these changes the boss did not start, after that change the boss is started as it should

Merge All Branch

### CODE REVIEW

**Review by coolzoom — APPROVED** [review]

**Review by coolzoom — APPROVED** [review]

**Comment by talamortis** [comment]
Going to test something before I merge this, need to check see if the boss is activated by an area trigger. If not will merge and nice work @vhiperdev

**Comment by talamortis** [comment]
@vhiperdev have you only pushed this to the Eluna branch?

**Comment by vhiperdev** [comment]
> @vhiperdev have you only pushed this to the Eluna branch?
This fix I made in the eluna branch most can merge at all

**Comment by yuanf225** [comment]
This should only be pushed to the master

**Comment by talamortis** [comment]
Thanks for this @vhiperdev  will merge :)

**Pull request merged**
