### PR TITLE
Restructure : change oregoncore file system structure

### PR DESCRIPTION
**Pull request by coolzoom**
nothing fancy, just easier for us to compare and make changes.
- [x] tools
- [x] collision
- [x] framework
- [x] shared
- [x] authserver
- [x] worldserver
- [x] game
- [x] scripts

### CODE REVIEW

**Comment by coolzoom** [comment]
this is just file/folder position change, should not do any damage to the core itself.
All the changes are related to the CMAKE file(path of the source) and the cpp file "include" path.
These changes make the file system more tidy and clean, and very close to the current trinitycore/3.3.5 branch. which allows us to compare and make changes a lot easier.
but have to be clear that there's still a lot of files position/structure not match with TC because back in the day oregoncore had been changed a lot combining mangos/early trinty/current trinity and some old/modern structures from many developers/contributors by heart.

**Comment by coolzoom** [comment]
mission complete, I did a sanity check should be fine now. please review when you have a chance @talamortis

**Comment by vhiperdev** [comment]
Good work @coolzoom at every moment the structure of this repository is getting even better so that we can work and leave as stable as possible, similar to the 3.3.5a repositories

I will test and give my feedback

**Comment by talamortis** [comment]
Thanks for this @coolzoom.

@vhiperdev are you able to test these changes if so i will then merge :)

**Comment by vhiperdev** [comment]
@coolzoom @talamortis 

Built successfully!!

image

It would also be good to upgrade to **Branch=Eluna** in TC has a folder called **LuaEngine** or in the future make a module like did AzerothCore

**Comment by talamortis** [comment]
Thanks for testing @vhiperdev  i will now merge 👍

**Pull request merged**
