### PR TITLE
remove redundant code for item and player gossip

### PR DESCRIPTION
**Pull request by coolzoom**
those codes were the reason of why the gossip select not functional

### CODE REVIEW

**Comment by talamortis** [comment]
is this just todo with eluna?

**Comment by vhiperdev** [comment]
Yes that works only with Eluna it is necessary to have it

**Comment by coolzoom** [comment]
@vhiperdev I found it already hooked in scriptMgr. do you mean the eluna item gossip wont work without this? 
the c++ version item gossip won't work because of those lines.

**Comment by vhiperdev** [comment]
@coolzoom We can improve I think
 
I see how it works in TrinityCore
https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/blob/master/src/server/game/Handlers/MiscHandler.cpp#L182

**Comment by talamortis** [comment]
Instead of commenting out the code can we not just remove it?

**Comment by coolzoom** [comment]
yes can delete it without any issue. both eluna and c++ item gossip should work normally

**Comment by talamortis** [comment]
can you remove it then ill merge into core :) thanks again @coolzoom

**Comment by coolzoom** [comment]
@talamortis all right, done

**Pull request merged**
