### PR TITLE
Open ssl

### PR DESCRIPTION
**Pull request by ReyDonovan**
Update cmake OpenSSL support version 1.0.0 1.0.2 1.1.0 1.1.1

pls test debug mode and if crashe -> crashe log me

### CODE REVIEW

**Comment by talamortis** [comment]
Has this been tested with warden enabled?

**Comment by ReyDonovan** [comment]
@talamortis  not need test enable Warden

**Comment by vhiperdev** [comment]
Test this PR with Warden enabled apparently this OpenSSl update is working.

**WINDOWS 10 VS 2017**

In the old PR when logging in the game the Crash server ..

Good job @ReyDonovan 

```
Warden.Enabled = 1
Warden.Kick = 0
Warden.NumChecks = 10
Warden.ClientResponseDelay = 90
Warden.ClientCheckHoldOff = 15
Warden.LogFile = "warden.log"
```

image
image
=====================================
**Ubuntu 18.04**
OpenSSL 1.1.1  11 Sep 2018

image

**Review by vhiperdev — APPROVED** [review]

**Comment by ReyDonovan** [comment]
these PRs are just preparations for a major restructuring of the emulator file system and the introduction of new libraries)
I'm used to working on fresh software

Новый точечный рисунок
my old nick zgn1988

I just don’t remember the password for this account

**Review by vhiperdev — APPROVED** [review]

**Comment by talamortis** [comment]
Thanks for testing @vhiperdev  and thanks for the PR @ReyDonovan will merge

**Pull request merged**
