### PR TITLE
Merge master into Eluna branch and fixed compile

### PR DESCRIPTION
**Pull request by coolzoom**

### CODE REVIEW

**Comment by vhiperdev** [comment]
@coolzoom @talamortis 

It built successfully, but I found that the command `.reload eluna` isn't it working for me in the image below the npc transmogrifer.lua is working.

command to reload the scripts from the 'Lua_scripts' folder does not work, I wonder if all functions are working correctly not da to test all.

image

**Comment by yuanf225** [comment]
Yes, it is necessary to confirm whether eluna and modules are loaded and effective

**Comment by coolzoom** [comment]
@vhiperdev @yuanf225 does reload work before merge? please test

**Comment by coolzoom** [comment]
> The way to enable eluna is not the default? Modified to choose by yourself before compiling

Yes non-blizlike contents have to be off by default in cmake

**Comment by coolzoom** [comment]
@talamortis added eluna option in cmake, prob we can change eluna to master and only maintain one branch

**Comment by talamortis** [comment]
Nice, Thanks for this also is the reload command working for Eluna if so then ill merge and since we have the cmake option now I don't mind merging into master and work from 1 branch.

**Comment by coolzoom** [comment]
Haven’t got a chance to test, will test when I get back to home. It shouldn’t broken and weird since I didn’t touch the OnCommand part it was simple merge and move

**Comment by coolzoom** [comment]
image
should be fine now.

**Comment by vhiperdev** [comment]
Good job @coolzoom is now working agree to leaves only 1 Branch now that Eluna is optional in Cmake @talamortis 

image

**Comment by coolzoom** [comment]
merging eluna into master may have a lot of conflicts. I did a file to file compare between master/eluna during adding eluna switch, probably can just rename/create a new master branch based on eluna branch.

btw, I checked the azerothcore eluna module, realize there is no need to convert our current eluna into a module because we already have a switch in cmake, the mod-eluna module at az is changing the include file linking during cmake and enable the cmake ELUNA defines.. it still having eluna hook everywhere. https://github.com/azerothcore/azerothcore-wotlk/blob/e3a81ad180a83805a1b0226d62aaee00be9d17c8/src/server/game/Entities/Player/Player.cpp#L81

**Comment by talamortis** [comment]
Thanks for testing @vhiperdev  will now merge and also push into master branch! 👍

**Pull request merged**
